package com.muses.data.mapper;

import com.muses.data.model.SuoodActivity;
import com.muses.data.model.SuoodActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuoodActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int countByExample(SuoodActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int deleteByExample(SuoodActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int deleteByPrimaryKey(Integer activity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int insert(SuoodActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int insertSelective(SuoodActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    List<SuoodActivity> selectByExample(SuoodActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    SuoodActivity selectByPrimaryKey(Integer activity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") SuoodActivity record, @Param("example") SuoodActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int updateByExample(@Param("record") SuoodActivity record, @Param("example") SuoodActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int updateByPrimaryKeySelective(SuoodActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    int updateByPrimaryKey(SuoodActivity record);
}