package com.muses.data.model;

public class SuoodActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_id
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_title
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private String activity_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_type
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private String activity_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_banner
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private String activity_banner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_style
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private String activity_style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_desc
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private String activity_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_start_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private Integer activity_start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_end_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private Integer activity_end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_sort
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private Boolean activity_sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_state
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    private Boolean activity_state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_id
     *
     * @return the value of suood_activity.activity_id
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_id
     *
     * @param activity_id the value for suood_activity.activity_id
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_title
     *
     * @return the value of suood_activity.activity_title
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public String getActivity_title() {
        return activity_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_title
     *
     * @param activity_title the value for suood_activity.activity_title
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_title(String activity_title) {
        this.activity_title = activity_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_type
     *
     * @return the value of suood_activity.activity_type
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public String getActivity_type() {
        return activity_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_type
     *
     * @param activity_type the value for suood_activity.activity_type
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_type(String activity_type) {
        this.activity_type = activity_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_banner
     *
     * @return the value of suood_activity.activity_banner
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public String getActivity_banner() {
        return activity_banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_banner
     *
     * @param activity_banner the value for suood_activity.activity_banner
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_banner(String activity_banner) {
        this.activity_banner = activity_banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_style
     *
     * @return the value of suood_activity.activity_style
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public String getActivity_style() {
        return activity_style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_style
     *
     * @param activity_style the value for suood_activity.activity_style
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_style(String activity_style) {
        this.activity_style = activity_style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_desc
     *
     * @return the value of suood_activity.activity_desc
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public String getActivity_desc() {
        return activity_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_desc
     *
     * @param activity_desc the value for suood_activity.activity_desc
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_desc(String activity_desc) {
        this.activity_desc = activity_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_start_date
     *
     * @return the value of suood_activity.activity_start_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public Integer getActivity_start_date() {
        return activity_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_start_date
     *
     * @param activity_start_date the value for suood_activity.activity_start_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_start_date(Integer activity_start_date) {
        this.activity_start_date = activity_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_end_date
     *
     * @return the value of suood_activity.activity_end_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public Integer getActivity_end_date() {
        return activity_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_end_date
     *
     * @param activity_end_date the value for suood_activity.activity_end_date
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_end_date(Integer activity_end_date) {
        this.activity_end_date = activity_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_sort
     *
     * @return the value of suood_activity.activity_sort
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public Boolean getActivity_sort() {
        return activity_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_sort
     *
     * @param activity_sort the value for suood_activity.activity_sort
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_sort(Boolean activity_sort) {
        this.activity_sort = activity_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_state
     *
     * @return the value of suood_activity.activity_state
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public Boolean getActivity_state() {
        return activity_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_state
     *
     * @param activity_state the value for suood_activity.activity_state
     *
     * @mbggenerated Thu Dec 31 02:00:32 CST 2015
     */
    public void setActivity_state(Boolean activity_state) {
        this.activity_state = activity_state;
    }
}