package com.muses.data.model;

import java.util.Date;

public class SmsIdentifyCode1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_identifycode.id
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_identifycode.invalidDate
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    private Date invalidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_identifycode.codeType
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_identifycode.mobileNo
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_identifycode.validCode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    private String validCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_identifycode.id
     *
     * @return the value of t_sms_identifycode.id
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_identifycode.id
     *
     * @param id the value for t_sms_identifycode.id
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_identifycode.invalidDate
     *
     * @return the value of t_sms_identifycode.invalidDate
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_identifycode.invalidDate
     *
     * @param invalidDate the value for t_sms_identifycode.invalidDate
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_identifycode.codeType
     *
     * @return the value of t_sms_identifycode.codeType
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public Integer getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_identifycode.codeType
     *
     * @param codeType the value for t_sms_identifycode.codeType
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_identifycode.mobileNo
     *
     * @return the value of t_sms_identifycode.mobileNo
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_identifycode.mobileNo
     *
     * @param mobileNo the value for t_sms_identifycode.mobileNo
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_identifycode.validCode
     *
     * @return the value of t_sms_identifycode.validCode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_identifycode.validCode
     *
     * @param validCode the value for t_sms_identifycode.validCode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode;
    }
}