package com.muses.data.model;

public class ActivityRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_title
     *
     * @mbggenerated
     */
    private String activityTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_type
     *
     * @mbggenerated
     */
    private String activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_banner
     *
     * @mbggenerated
     */
    private String activityBanner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_style
     *
     * @mbggenerated
     */
    private String activityStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_desc
     *
     * @mbggenerated
     */
    private String activityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_start_date
     *
     * @mbggenerated
     */
    private Integer activityStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_end_date
     *
     * @mbggenerated
     */
    private Integer activityEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_sort
     *
     * @mbggenerated
     */
    private Boolean activitySort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_activity.activity_state
     *
     * @mbggenerated
     */
    private Boolean activityState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_id
     *
     * @return the value of suood_activity.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_id
     *
     * @param activityId the value for suood_activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_title
     *
     * @return the value of suood_activity.activity_title
     *
     * @mbggenerated
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_title
     *
     * @param activityTitle the value for suood_activity.activity_title
     *
     * @mbggenerated
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle == null ? null : activityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_type
     *
     * @return the value of suood_activity.activity_type
     *
     * @mbggenerated
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_type
     *
     * @param activityType the value for suood_activity.activity_type
     *
     * @mbggenerated
     */
    public void setActivityType(String activityType) {
        this.activityType = activityType == null ? null : activityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_banner
     *
     * @return the value of suood_activity.activity_banner
     *
     * @mbggenerated
     */
    public String getActivityBanner() {
        return activityBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_banner
     *
     * @param activityBanner the value for suood_activity.activity_banner
     *
     * @mbggenerated
     */
    public void setActivityBanner(String activityBanner) {
        this.activityBanner = activityBanner == null ? null : activityBanner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_style
     *
     * @return the value of suood_activity.activity_style
     *
     * @mbggenerated
     */
    public String getActivityStyle() {
        return activityStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_style
     *
     * @param activityStyle the value for suood_activity.activity_style
     *
     * @mbggenerated
     */
    public void setActivityStyle(String activityStyle) {
        this.activityStyle = activityStyle == null ? null : activityStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_desc
     *
     * @return the value of suood_activity.activity_desc
     *
     * @mbggenerated
     */
    public String getActivityDesc() {
        return activityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_desc
     *
     * @param activityDesc the value for suood_activity.activity_desc
     *
     * @mbggenerated
     */
    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc == null ? null : activityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_start_date
     *
     * @return the value of suood_activity.activity_start_date
     *
     * @mbggenerated
     */
    public Integer getActivityStartDate() {
        return activityStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_start_date
     *
     * @param activityStartDate the value for suood_activity.activity_start_date
     *
     * @mbggenerated
     */
    public void setActivityStartDate(Integer activityStartDate) {
        this.activityStartDate = activityStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_end_date
     *
     * @return the value of suood_activity.activity_end_date
     *
     * @mbggenerated
     */
    public Integer getActivityEndDate() {
        return activityEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_end_date
     *
     * @param activityEndDate the value for suood_activity.activity_end_date
     *
     * @mbggenerated
     */
    public void setActivityEndDate(Integer activityEndDate) {
        this.activityEndDate = activityEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_sort
     *
     * @return the value of suood_activity.activity_sort
     *
     * @mbggenerated
     */
    public Boolean getActivitySort() {
        return activitySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_sort
     *
     * @param activitySort the value for suood_activity.activity_sort
     *
     * @mbggenerated
     */
    public void setActivitySort(Boolean activitySort) {
        this.activitySort = activitySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_activity.activity_state
     *
     * @return the value of suood_activity.activity_state
     *
     * @mbggenerated
     */
    public Boolean getActivityState() {
        return activityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_activity.activity_state
     *
     * @param activityState the value for suood_activity.activity_state
     *
     * @mbggenerated
     */
    public void setActivityState(Boolean activityState) {
        this.activityState = activityState;
    }
}