package com.muses.data.model;

public class AdminDataRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_name
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_password
     *
     * @mbggenerated
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_login_time
     *
     * @mbggenerated
     */
    private Integer adminLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_login_num
     *
     * @mbggenerated
     */
    private Integer adminLoginNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_is_super
     *
     * @mbggenerated
     */
    private Boolean adminIsSuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suood_admin.admin_gid
     *
     * @mbggenerated
     */
    private Short adminGid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_id
     *
     * @return the value of suood_admin.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_id
     *
     * @param adminId the value for suood_admin.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_name
     *
     * @return the value of suood_admin.admin_name
     *
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_name
     *
     * @param adminName the value for suood_admin.admin_name
     *
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_password
     *
     * @return the value of suood_admin.admin_password
     *
     * @mbggenerated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_password
     *
     * @param adminPassword the value for suood_admin.admin_password
     *
     * @mbggenerated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_login_time
     *
     * @return the value of suood_admin.admin_login_time
     *
     * @mbggenerated
     */
    public Integer getAdminLoginTime() {
        return adminLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_login_time
     *
     * @param adminLoginTime the value for suood_admin.admin_login_time
     *
     * @mbggenerated
     */
    public void setAdminLoginTime(Integer adminLoginTime) {
        this.adminLoginTime = adminLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_login_num
     *
     * @return the value of suood_admin.admin_login_num
     *
     * @mbggenerated
     */
    public Integer getAdminLoginNum() {
        return adminLoginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_login_num
     *
     * @param adminLoginNum the value for suood_admin.admin_login_num
     *
     * @mbggenerated
     */
    public void setAdminLoginNum(Integer adminLoginNum) {
        this.adminLoginNum = adminLoginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_is_super
     *
     * @return the value of suood_admin.admin_is_super
     *
     * @mbggenerated
     */
    public Boolean getAdminIsSuper() {
        return adminIsSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_is_super
     *
     * @param adminIsSuper the value for suood_admin.admin_is_super
     *
     * @mbggenerated
     */
    public void setAdminIsSuper(Boolean adminIsSuper) {
        this.adminIsSuper = adminIsSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suood_admin.admin_gid
     *
     * @return the value of suood_admin.admin_gid
     *
     * @mbggenerated
     */
    public Short getAdminGid() {
        return adminGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suood_admin.admin_gid
     *
     * @param adminGid the value for suood_admin.admin_gid
     *
     * @mbggenerated
     */
    public void setAdminGid(Short adminGid) {
        this.adminGid = adminGid;
    }
}