package com.muses.data.model;

import java.util.ArrayList;
import java.util.List;

public class AdminDataRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public AdminDataRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("admin_name is null");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("admin_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("admin_name =", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("admin_name <>", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("admin_name >", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_name >=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("admin_name <", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("admin_name <=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("admin_name like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("admin_name not like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameIn(List<String> values) {
            addCriterion("admin_name in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotIn(List<String> values) {
            addCriterion("admin_name not in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("admin_name between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("admin_name not between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNull() {
            addCriterion("admin_password is null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNotNull() {
            addCriterion("admin_password is not null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordEqualTo(String value) {
            addCriterion("admin_password =", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotEqualTo(String value) {
            addCriterion("admin_password <>", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThan(String value) {
            addCriterion("admin_password >", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("admin_password >=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThan(String value) {
            addCriterion("admin_password <", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThanOrEqualTo(String value) {
            addCriterion("admin_password <=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLike(String value) {
            addCriterion("admin_password like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotLike(String value) {
            addCriterion("admin_password not like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIn(List<String> values) {
            addCriterion("admin_password in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotIn(List<String> values) {
            addCriterion("admin_password not in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordBetween(String value1, String value2) {
            addCriterion("admin_password between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotBetween(String value1, String value2) {
            addCriterion("admin_password not between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeIsNull() {
            addCriterion("admin_login_time is null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeIsNotNull() {
            addCriterion("admin_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeEqualTo(Integer value) {
            addCriterion("admin_login_time =", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeNotEqualTo(Integer value) {
            addCriterion("admin_login_time <>", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeGreaterThan(Integer value) {
            addCriterion("admin_login_time >", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_login_time >=", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeLessThan(Integer value) {
            addCriterion("admin_login_time <", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeLessThanOrEqualTo(Integer value) {
            addCriterion("admin_login_time <=", value, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeIn(List<Integer> values) {
            addCriterion("admin_login_time in", values, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeNotIn(List<Integer> values) {
            addCriterion("admin_login_time not in", values, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeBetween(Integer value1, Integer value2) {
            addCriterion("admin_login_time between", value1, value2, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_login_time not between", value1, value2, "adminLoginTime");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumIsNull() {
            addCriterion("admin_login_num is null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumIsNotNull() {
            addCriterion("admin_login_num is not null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumEqualTo(Integer value) {
            addCriterion("admin_login_num =", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumNotEqualTo(Integer value) {
            addCriterion("admin_login_num <>", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumGreaterThan(Integer value) {
            addCriterion("admin_login_num >", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_login_num >=", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumLessThan(Integer value) {
            addCriterion("admin_login_num <", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumLessThanOrEqualTo(Integer value) {
            addCriterion("admin_login_num <=", value, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumIn(List<Integer> values) {
            addCriterion("admin_login_num in", values, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumNotIn(List<Integer> values) {
            addCriterion("admin_login_num not in", values, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumBetween(Integer value1, Integer value2) {
            addCriterion("admin_login_num between", value1, value2, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminLoginNumNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_login_num not between", value1, value2, "adminLoginNum");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperIsNull() {
            addCriterion("admin_is_super is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperIsNotNull() {
            addCriterion("admin_is_super is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperEqualTo(Boolean value) {
            addCriterion("admin_is_super =", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperNotEqualTo(Boolean value) {
            addCriterion("admin_is_super <>", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperGreaterThan(Boolean value) {
            addCriterion("admin_is_super >", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperGreaterThanOrEqualTo(Boolean value) {
            addCriterion("admin_is_super >=", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperLessThan(Boolean value) {
            addCriterion("admin_is_super <", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperLessThanOrEqualTo(Boolean value) {
            addCriterion("admin_is_super <=", value, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperIn(List<Boolean> values) {
            addCriterion("admin_is_super in", values, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperNotIn(List<Boolean> values) {
            addCriterion("admin_is_super not in", values, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperBetween(Boolean value1, Boolean value2) {
            addCriterion("admin_is_super between", value1, value2, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminIsSuperNotBetween(Boolean value1, Boolean value2) {
            addCriterion("admin_is_super not between", value1, value2, "adminIsSuper");
            return (Criteria) this;
        }

        public Criteria andAdminGidIsNull() {
            addCriterion("admin_gid is null");
            return (Criteria) this;
        }

        public Criteria andAdminGidIsNotNull() {
            addCriterion("admin_gid is not null");
            return (Criteria) this;
        }

        public Criteria andAdminGidEqualTo(Short value) {
            addCriterion("admin_gid =", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidNotEqualTo(Short value) {
            addCriterion("admin_gid <>", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidGreaterThan(Short value) {
            addCriterion("admin_gid >", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidGreaterThanOrEqualTo(Short value) {
            addCriterion("admin_gid >=", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidLessThan(Short value) {
            addCriterion("admin_gid <", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidLessThanOrEqualTo(Short value) {
            addCriterion("admin_gid <=", value, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidIn(List<Short> values) {
            addCriterion("admin_gid in", values, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidNotIn(List<Short> values) {
            addCriterion("admin_gid not in", values, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidBetween(Short value1, Short value2) {
            addCriterion("admin_gid between", value1, value2, "adminGid");
            return (Criteria) this;
        }

        public Criteria andAdminGidNotBetween(Short value1, Short value2) {
            addCriterion("admin_gid not between", value1, value2, "adminGid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table suood_admin
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}