package com.muses.data.mapper;

import com.muses.data.model.SmsIdentifyCode1;
import com.muses.data.model.SmsIdentifyCode1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsIdentifyCode1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int countByExample(SmsIdentifyCode1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int deleteByExample(SmsIdentifyCode1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int insert(SmsIdentifyCode1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int insertSelective(SmsIdentifyCode1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    List<SmsIdentifyCode1> selectByExample(SmsIdentifyCode1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    SmsIdentifyCode1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") SmsIdentifyCode1 record, @Param("example") SmsIdentifyCode1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int updateByExample(@Param("record") SmsIdentifyCode1 record, @Param("example") SmsIdentifyCode1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int updateByPrimaryKeySelective(SmsIdentifyCode1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:30:43 CST 2015
     */
    int updateByPrimaryKey(SmsIdentifyCode1 record);
}