package com.muses.data.mapper;

import com.muses.data.model.SmsIdentifyCode;
import com.muses.data.model.SmsIdentifyCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsIdentifyCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int countByExample(SmsIdentifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int deleteByExample(SmsIdentifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int insert(SmsIdentifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int insertSelective(SmsIdentifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    List<SmsIdentifyCode> selectByExample(SmsIdentifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    SmsIdentifyCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") SmsIdentifyCode record, @Param("example") SmsIdentifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int updateByExample(@Param("record") SmsIdentifyCode record, @Param("example") SmsIdentifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int updateByPrimaryKeySelective(SmsIdentifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_identifycode
     *
     * @mbggenerated Thu Dec 17 18:28:29 CST 2015
     */
    int updateByPrimaryKey(SmsIdentifyCode record);
}