package com.muses.data.mapper;

import com.muses.data.model.ActivityRecord;
import com.muses.data.model.ActivityRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int countByExample(ActivityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int insert(ActivityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int insertSelective(ActivityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    List<ActivityRecord> selectByExample(ActivityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    ActivityRecord selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityRecord record, @Param("example") ActivityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityRecord record, @Param("example") ActivityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityRecord record);
}