package com.muses.data.mapper;

import com.muses.data.model.AdminOperationLogRecord;
import com.muses.data.model.AdminOperationLogRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminOperationLogRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int countByExample(AdminOperationLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int deleteByExample(AdminOperationLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int insert(AdminOperationLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int insertSelective(AdminOperationLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    List<AdminOperationLogRecord> selectByExample(AdminOperationLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    AdminOperationLogRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminOperationLogRecord record, @Param("example") AdminOperationLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminOperationLogRecord record, @Param("example") AdminOperationLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminOperationLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminOperationLogRecord record);
}