package com.muses.data.mapper;

import com.muses.data.model.AdminDataRecord;
import com.muses.data.model.AdminDataRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminDataRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int countByExample(AdminDataRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int deleteByExample(AdminDataRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int insert(AdminDataRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int insertSelective(AdminDataRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    List<AdminDataRecord> selectByExample(AdminDataRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    AdminDataRecord selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminDataRecord record, @Param("example") AdminDataRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminDataRecord record, @Param("example") AdminDataRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminDataRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suood_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminDataRecord record);
}